version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\linquize\test1

environment:
  GOPATH: c:\gopath

stack: go 1.11

install:
  - git config -l --system
  - git config -l --global
  - git config -l --local
  - git config -l
  - git config core.autocrlf
  - set PATH=%GOPATH%\bin;%PATH%
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - go version
  - go env
